# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.6.6'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', ' 5.2.4.4'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '>= 3.12.3'
gem 'bootsnap', '>= 1.1.0', require: false

gem 'sass-rails', '~> 5.1'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 5.0.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby
gem 'mini_racer'
# Use jquery as the JavaScript library
gem 'jquery-rails', '~> 4.3.4'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.10'
gem 'webpacker', '~> 3.0'

# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# UTIL: Templates
gem 'slim-rails', '~> 3.2.0'
# UTIL: Grid
gem 'bootstrap-sass', '~> 3.4.1'
# # UTIL Image y File Manager
gem 'paperclip', '~> 5.2.1'
gem 'image_processing', '~> 1.10'
gem 'mini_magick', '~> 4.9.5'
gem 'active_storage_validations', '~> 0.8.7'

# UTIL: Autoprefixer
gem 'autoprefixer-rails', '~> 6.6.1'
# UTIL: Simple Form
gem 'simple_form', '~> 5.0'
# # UTIL: Session en BBDD
gem 'activerecord-session_store', '~> 1.0'
# UTIL: Friendly ID
gem 'friendly_id', '~> 5.4.0'
# AUTH
gem 'devise', '4.7.1'
gem 'devise_invitable', '~> 2.0.0'
gem 'devise-bootstrap-views', '~> 0.0.10'
gem 'cancancan', '~> 1.17.0'

# # SEO
gem 'metamagic', '~> 3.1.7'
# PAGINACION
gem 'kaminari', '1.2.1'
gem 'bootstrap-kaminari-views', '~> 0.0.5'
gem 'bootstrap4-kaminari-views'

# SELECT2
gem 'select2-rails', '3.5.9.3'
# MODALES JAVASCRIPT
gem 'lightbox2-rails', '~> 2.8.2'
# UITL: Ckeditor
# # gem 'ckeditor', github: 'galetahub/ckeditor'
gem 'ckeditor', '~> 4.3.0'
gem 'actiontext', github: 'kobaltz/actiontext', branch: 'archive', require: 'action_text'
# MIGAS
gem 'breadcrumbs_on_rails', '~> 3.0.1'

# MAILING
gem 'premailer-rails'
gem 'sendinblue', '~> 2.4'

# ADMIN THEME
gem 'adminlte2-rails', '0.0.5'
gem 'icheck-rails', '~> 1.0.2'
gem 'font-awesome-rails', '~> 4.7.0'
gem 'momentjs-rails', '~> 2.17.1'
gem 'bootstrap-daterangepicker-rails', '~> 0.1'

# ADMIN 2
gem 'nested_form_fields'
gem 'ransack', '~> 2.3.2'

# FROTEND
gem 'modernizr-rails', '~> 2.7.1'
gem 'owlcarousel-rails', '~> 1.1.3'
gem 'prettyphoto-rails', '~> 0.2.1'
gem 'flexslider-rails', '~> 1.0'
gem 'social-share-button', '~> 0.8'
gem 'cookies_eu', '~> 1.6.1'

gem 'dotenv-rails', require: 'dotenv/rails-now'

gem 'dalli', '~> 2.7.11'
gem 'dropzonejs-rails', '~> 0.7.4'
gem 'swipebox', '~> 1.4.4'

# LOG REPORT
gem 'bugsnag'

# sidekiq
gem 'sidekiq'

# for api v3 development
gem 'rack-cors', '~> 1.1'
# gem 'bcrypt', '~> 3.1.7'
gem 'jwt'

# EXTRAS
gem 'acts_as_paranoid', '~> 0.7.0'
gem 'webdack-uuid_migration', '~> 1.3'

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'awesome_print'
  gem 'meta_request'
  gem 'capistrano-rails', '~> 1.6.0'
  gem 'capistrano-bundler', '~> 2.0.0'
  gem 'capistrano-rvm', '~> 0.1.2'
  gem 'capistrano3-puma', '~> 4.0.0'
  gem 'capistrano-sidekiq', '~> 1.0.3'
  gem 'capistrano-local-precompile', require: false
  gem 'capistrano-rails-db', '~> 0.0.2'
  gem 'capistrano-yarn'
  gem 'bugsnag-capistrano', require: false
  gem 'overcommit'
  gem 'rubocop', '~> 1.0'
  gem 'rubocop-rails', '~> 2.8.1'
  gem 'rubocop-performance', '~> 1.8.1'
  gem 'slim_lint'
  gem 'letter_opener_web', '~> 1.3.4'
  gem 'unicode-display_width', '>= 1.3.3'
  gem 'html2slim'
end

group :test do
  gem 'fuubar', '~> 2.3.2'
  gem 'json-schema', '~> 2.8.1'
  gem 'rails-controller-testing', '~> 1.0.4'
  gem 'shoulda-matchers', '4.0.0.rc1'
  gem 'simplecov', require: false
end

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'pry-rails', '~> 0.3.9'
  gem 'pry-byebug', '~> 3.9.0'
  gem 'factory_bot_rails', '~> 4.11.1'
  gem 'faker', '~> 2.14.0'
  gem 'rspec-rails', '~> 3.8.1'
  gem 'database_cleaner', '~> 1.7.0'
  gem 'annotate'
  gem 'oj', '~> 3.10.15'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
